import {
  ArrowRight,
  BookOpen,
  CalendarDays,
  Camera,
  Check,
  CheckCheck,
  ChevronDown,
  Copy,
  Flower2,
  Heart,
  House,
  Mail,
  Map,
  MapPin,
  Maximize,
  Menu,
  Minimize,
  Music2,
  Navigation,
  Pause,
  Play,
  RotateCcw,
  Send,
  Sparkles,
  Sprout,
  TreeDeciduous,
  Users,
  Volume2,
  VolumeX,
  X,
} from 'lucide-react';
const icons = {
  arrow: ArrowRight,
  book: BookOpen,
  calendar: CalendarDays,
  camera: Camera,
  check: Check,
  checks: CheckCheck,
  down: ChevronDown,
  copy: Copy,
  flower: Flower2,
  heart: Heart,
  home: House,
  mail: Mail,
  map: Map,
  pin: MapPin,
  fullscreen: Maximize,
  menu: Menu,
  minimize: Minimize,
  music: Music2,
  navigation: Navigation,
  pause: Pause,
  play: Play,
  restart: RotateCcw,
  send: Send,
  sparkles: Sparkles,
  sprout: Sprout,
  tree: TreeDeciduous,
  users: Users,
  volume: Volume2,
  muted: VolumeX,
  close: X,
};
export function Icon({
  name,
  size = 20,
  className = '',
}: {
  name: string;
  size?: number;
  className?: string;
}) {
  const Component = icons[name as keyof typeof icons] ?? Flower2;
  return <Component size={size} strokeWidth={1.5} className={className} aria-hidden="true" />;
}
